allowBuilds:
    "@parcel/watcher": true
    "@swc/core": true
    esbuild: true
includeWorkspaceRoot: true
packages:
    - "packages/*"
catalog:
    react: 19.2.6
    react-dom: 19.2.6
    "@types/react": 19.2.14
    "@types/react-dom": 19.2.3
overrides:
    react: "catalog:"
    react-dom: "catalog:"
    "@types/react": "catalog:"
    "@types/react-dom": "catalog:"
