apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: workflow-ui-ingress
    namespace: "{{ .Release.Namespace }}"
    annotations:
        kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
        nginx.ingress.kubernetes.io/proxy-body-size: 5m
        nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Content-Type-Options: nosniff";
            more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
            more_set_headers "Referrer-Policy: no-referrer";
            more_set_headers "Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
            {{- if .Values.contentSecurityPolicy }}
            more_set_headers "Content-Security-Policy: {{ .Values.contentSecurityPolicy }}";
            {{- end }}
spec:
    tls:
        - hosts:
              - "{{ .Values.hostname }}"
          {{- if .Values.azure }}
          secretName: ingress-tls-csi-workflow-ui
          {{- end }}
    rules:
        - host: "{{ .Values.hostname }}"
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: workflow-ui
                            port:
                                number: 80
