hostname: workflow-ui.local
ingressClass: nginx
image: datanosecr.azurecr.io/workflow-ui
tag: latest
certificateName: milestones-fnwi-uva-nl
contentSecurityPolicy: "default-src 'self'"

envVars:
    webapiUrl: ""
    env: "development"
    authAuthority: ""
    authClientId: ""
    authLogoutUrl: ""
