hostname: workflow-ui.local
ingressClass: nginx
image: datanosecr.azurecr.io/workflow-ui
tag: latest
certificateName: datanose-nl # Used later for secretproviderclass

envVars:
    webapiUrl: ""
    env: "development"
    authAuthority: ""
    authClientId: ""
    authLogoutUrl: ""
