// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
    common: {
        language: "Language";
        language_en: "English";
        language_nl: "Dutch";
    };
    workflow: {
        cancel: "Cancel";
        confirm: "Confirm";
        first_help: {
            title: "First aid with thesis";
        };
        good_to_know: {
            title: "Handy during your thesis";
        };
        progress: {
            label: "Here's where you are in the process";
            title: "Progress";
        };
        screens: {
            dynamic: {
                "assign-subject": "Assign topic";
                completed: "Completed";
                "thesis-in-progress": "Thesis in progress";
            };
            students: "Students";
        };
    };
}

export default Resources;
