// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
    common: {
        language: "Language";
        language_en: "English";
        language_nl: "Dutch";
    };
}

export default Resources;
