// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
    common: {
        language: "Language";
        language_en: "English";
        language_nl: "Dutch";
    };
    workflow: {
        progress: {
            label: "Here's where you are in the process";
            title: "Progress";
        };
    };
}

export default Resources;
