name: build and deploy

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build and push container
              env:
                  NPM_TOKEN: ${{ secrets.FA_NPM_TOKEN }}
              run: |
                  set -euxo pipefail
                  docker build -f Dockerfile --build-arg npm_token=${NPM_TOKEN} -t "datanosecr.azurecr.io/workflow-ui:latest" .
                  docker push "datanosecr.azurecr.io/workflow-ui:latest"

            - name: Push chart and deploy
              env:
                  UPDATER_SECRET: ${{ secrets.UPDATER_SECRET_DN }}
              run: |
                  VERSION=$(date "+1.0.%Y%m%d%H%M%S")
                  helm package --version "${VERSION}" --app-version "${VERSION}" charts/workflow-ui
                  helm push "workflow-ui-${VERSION}.tgz" oci://datanosecr.azurecr.io/helm
                  curl "https://api-v2-tst.datanose.nl/gitops-updater?name=workflow-ui-tst&secret=${UPDATER_SECRET}&version=${VERSION}"
                  curl "https://api-v2-tst.datanose.nl/gitops-updater?name=workflow-ui-acc&secret=${UPDATER_SECRET}&version=${VERSION}"
