name: build and deploy UI library

on:
    push:
        branches: ["main"]
        paths:
            - packages/ui/**

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build and push container
              working-directory: ./packages/ui
              run: |
                  set -euxo pipefail
                  docker build -f Dockerfile -t "datanosecr.azurecr.io/storybook-ui:latest" .
                  docker push "datanosecr.azurecr.io/storybook-ui:latest"

            - name: Push chart and deploy
              env:
                  UPDATER_SECRET: ${{ secrets.UPDATER_SECRET_DN }}
              run: |
                  VERSION=$(date "+1.0.%Y%m%d%H%M%S")
                  helm package --version "${VERSION}" --app-version "${VERSION}" charts/storybook-ui
                  helm push "storybook-ui-${VERSION}.tgz" oci://datanosecr.azurecr.io/helm
                  curl "https://api-v2-tst.datanose.nl/gitops-updater?name=storybook-ui&secret=${UPDATER_SECRET}&version=${VERSION}"
