name: Check for smells
on:
    pull_request:
        branches: ["main"]

jobs:
    check-all:
        name: Lint & Format checks
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
            - name: Setup pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Prettier
              run: pnpm run format:check
            - name: Lint
              if: always()
              run: pnpm run lint
            - name: Translations
              if: always()
              run: pnpm run translations:check
