name: Cleanup PR deployment

on:
    pull_request:
        branches:
            - main
        types: [closed]

jobs:
    cleanup:
        runs-on: self-hosted
        steps:
            - name: Cleanup PR deployment
              run: |
                  curl "https://api-v2-tst.datanose.nl/gitops-updater?name=workflow-ui-pr&secret=${{ secrets.UPDATER_SECRET_DN }}&version=delete&id=${{ github.event.pull_request.number }}"
                  curl "https://api-v2-tst.datanose.nl/gitops-updater?name=storybook-ui-pr&secret=${{ secrets.UPDATER_SECRET_DN }}&version=delete&id=${{ github.event.pull_request.number }}"
